ignore:
  - "packages/gql/src/tracer.ts"
  - "packages/gql/src/job/job.ts"
  - "packages/gql/src/job/marketplace.job.ts"
  - "packages/gql/src/resolver/bid.resolver.ts"
  - "packages/gql/src/resolver/curation.resolver.ts"
  - "packages/gql/src/resolver/curation.resolver.ts"
  - "packages/gql/src/resolver/curation.resolver.ts"
  - "packages/gql/src/resolver/marketAsk.resolver.ts"
  - "packages/gql/src/resolver/marketSwap.resolver.ts"
  - "packages/gql/src/resolver/marketBid.resolver.ts"
  - "packages/gql/src/resolver/marketBid.resolver.ts"
  - "packages/gql/src/resolver/watchlist.resolver.ts"
  - "packages/gql/src/resolver/validation.ts"
  - "packages/gql/src/helper/websocketProvider.ts"
  - "packages/gql/src/defs/misc.ts"
  - "packages/gql/src/server.ts"
