version: "3.7"

services:
  redis:
    image: redis:alpine
    container_name: nftcom-redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - nftcom
    ports:
      - "10020:6379"
    volumes:
      - "redis:/var/lib/redis"
      - "redis:/usr/local/etc/redis/redis.conf"
    restart: unless-stopped

  redis-web:
    image: rediscommander/redis-commander:latest
    container_name: nftcom-redis-web
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - nftcom
    ports:
      - "10015:8081"
    depends_on:
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:13.4-alpine
    container_name: nftcom-db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
    networks:
      - nftcom
    ports:
      - "10030:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/
    restart: unless-stopped

#  gql:
#    build:
#      context: .
#      dockerfile: gql.Dockerfile
#    container_name: nftcom-gql
#    environment:
#      - DB_HOST=postgres
#      - DB_PORT=5432
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#    networks:
#      - nftcom
#    ports:
#      - "10010:10010"
##    volumes:
##      - "./src:/app/nftcom/src:cached"
#    depends_on:
#      - redis
#      - mongo
#    restart: unless-stopped

  # indexer:
  #   build:
  #     context: .
  #     dockerfile: indexer.Dockerfile
  #   container_name: nftcom-indexer
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   networks:
  #     - nftcom
  #   ports:
  #     - "9999:9999"
  # #    volumes:
  # #      - "./src:/app/nftcom/src:cached"
  #   depends_on:
  #     - redis
  #   restart: unless-stopped

volumes:
  postgres:
    name: nftcom-postgres
  redis:
    name: nftcom-redis

networks:
  nftcom:
    name: nftcom
