version: "3.7"

services:
#  redis:
#    image: redis:alpine
#    container_name: nftcom-redis
#    environment:
#      - REDIS_REPLICATION_MODE=master
#    networks:
#      - nftcom
#    ports:
#      - "6379:6379"
#    volumes:
#      - "nftcom-redis:/var/lib/redis"
#      - "nftcom-redis:/usr/local/etc/redis/redis.conf"
#    restart: unless-stopped
#
#  redis-web:
#    image: rediscommander/redis-commander:latest
#    container_name: nftcom-redis-web
#    environment:
#      - REDIS_HOSTS=local:redis:6379
#    networks:
#      - nftcom
#    ports:
#      - "9060:8081"
#    depends_on:
#      - redis
#    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: nftcom-mongo
    environment:
      - MONGO_INITDB_DATABASE=app
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - nftcom
    ports:
      - "27017:27017"
    volumes:
      - "mongo:/data/db:delegated"
    restart: unless-stopped

  mongo-web:
    image: mongo-express:latest
    container_name: nftcom-mongo-web
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    networks:
      - nftcom
    ports:
      - "10070:8081"
    depends_on:
      - mongo
    restart: unless-stopped

#  nftcom-server:
#    build:
#      context: .
#    container_name: nftcom-server
#    env_file: .env
#    networks:
#      - nftcom
#    ports:
#      - "10080:9080"
#    volumes:
#      - "./src:/app/nftcom/src:cached"
#    depends_on:
#      - redis
#      - mongo
#    restart: unless-stopped

volumes:
  mongo:
    name: nftcom-mongo
#  redis:
#    name: nftcom-redis

networks:
  nftcom:
    name: nftcom
