version: "3.7"

services:
  redis:
    image: redis:alpine
    container_name: nftcom-redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - nftcom
    ports:
      - "10020:6379"
    volumes:
      - "redis:/var/lib/redis"
      - "redis:/usr/local/etc/redis/redis.conf"
    restart: unless-stopped

  redis-web:
    image: rediscommander/redis-commander:latest
    container_name: nftcom-redis-web
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - nftcom
    ports:
      - "10015:8081"
    depends_on:
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:13.4-alpine
    container_name: nftcom-db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
    networks:
      - nftcom
    ports:
      - "10030:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/
    restart: unless-stopped

  postgres_tests:
    image: postgres:13.4-alpine
    container_name: nftcom-test-db
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
    networks:
      - nftcom
    ports:
      - "10031:5432"
    volumes:
      - postgres:/var/lib/postgresql-test/data/
    restart: unless-stopped

volumes:
  postgres:
    name: nftcom-postgres
  postgres_test:
    name: nftcom-postgres-test
  redis:
    name: nftcom-redis

networks:
  nftcom:
    name: nftcom
