/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace OrderTypes {
  export type TakerOrderStruct = {
    isOrderAsk: boolean;
    taker: string;
    price: BigNumberish;
    tokenId: BigNumberish;
    minPercentageToAsk: BigNumberish;
    params: BytesLike;
  };

  export type TakerOrderStructOutput = [
    boolean,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ] & {
    isOrderAsk: boolean;
    taker: string;
    price: BigNumber;
    tokenId: BigNumber;
    minPercentageToAsk: BigNumber;
    params: string;
  };

  export type MakerOrderStruct = {
    isOrderAsk: boolean;
    signer: string;
    collection: string;
    price: BigNumberish;
    tokenId: BigNumberish;
    amount: BigNumberish;
    strategy: string;
    currency: string;
    nonce: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    minPercentageToAsk: BigNumberish;
    params: BytesLike;
    v: BigNumberish;
    r: BytesLike;
    s: BytesLike;
  };

  export type MakerOrderStructOutput = [
    boolean,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    number,
    string,
    string
  ] & {
    isOrderAsk: boolean;
    signer: string;
    collection: string;
    price: BigNumber;
    tokenId: BigNumber;
    amount: BigNumber;
    strategy: string;
    currency: string;
    nonce: BigNumber;
    startTime: BigNumber;
    endTime: BigNumber;
    minPercentageToAsk: BigNumber;
    params: string;
    v: number;
    r: string;
    s: string;
  };
}

export interface LooksrareExchangeInterface extends utils.Interface {
  contractName: "LooksrareExchange";
  functions: {
    "DOMAIN_SEPARATOR()": FunctionFragment;
    "WETH()": FunctionFragment;
    "cancelAllOrdersForSender(uint256)": FunctionFragment;
    "cancelMultipleMakerOrders(uint256[])": FunctionFragment;
    "currencyManager()": FunctionFragment;
    "executionManager()": FunctionFragment;
    "isUserOrderNonceExecutedOrCancelled(address,uint256)": FunctionFragment;
    "matchAskWithTakerBid((bool,address,uint256,uint256,uint256,bytes),(bool,address,address,uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256,bytes,uint8,bytes32,bytes32))": FunctionFragment;
    "matchAskWithTakerBidUsingETHAndWETH((bool,address,uint256,uint256,uint256,bytes),(bool,address,address,uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256,bytes,uint8,bytes32,bytes32))": FunctionFragment;
    "matchBidWithTakerAsk((bool,address,uint256,uint256,uint256,bytes),(bool,address,address,uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256,bytes,uint8,bytes32,bytes32))": FunctionFragment;
    "owner()": FunctionFragment;
    "protocolFeeRecipient()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "royaltyFeeManager()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transferSelectorNFT()": FunctionFragment;
    "updateCurrencyManager(address)": FunctionFragment;
    "updateExecutionManager(address)": FunctionFragment;
    "updateProtocolFeeRecipient(address)": FunctionFragment;
    "updateRoyaltyFeeManager(address)": FunctionFragment;
    "updateTransferSelectorNFT(address)": FunctionFragment;
    "userMinOrderNonce(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelAllOrdersForSender",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMultipleMakerOrders",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "currencyManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isUserOrderNonceExecutedOrCancelled",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "matchAskWithTakerBid",
    values: [OrderTypes.TakerOrderStruct, OrderTypes.MakerOrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "matchAskWithTakerBidUsingETHAndWETH",
    values: [OrderTypes.TakerOrderStruct, OrderTypes.MakerOrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "matchBidWithTakerAsk",
    values: [OrderTypes.TakerOrderStruct, OrderTypes.MakerOrderStruct]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyFeeManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferSelectorNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateCurrencyManager",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateExecutionManager",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProtocolFeeRecipient",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRoyaltyFeeManager",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTransferSelectorNFT",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userMinOrderNonce",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelAllOrdersForSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMultipleMakerOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currencyManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUserOrderNonceExecutedOrCancelled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchAskWithTakerBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchAskWithTakerBidUsingETHAndWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchBidWithTakerAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltyFeeManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferSelectorNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCurrencyManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateExecutionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProtocolFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRoyaltyFeeManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTransferSelectorNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userMinOrderNonce",
    data: BytesLike
  ): Result;

  events: {
    "CancelAllOrders(address,uint256)": EventFragment;
    "CancelMultipleOrders(address,uint256[])": EventFragment;
    "NewCurrencyManager(address)": EventFragment;
    "NewExecutionManager(address)": EventFragment;
    "NewProtocolFeeRecipient(address)": EventFragment;
    "NewRoyaltyFeeManager(address)": EventFragment;
    "NewTransferSelectorNFT(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RoyaltyPayment(address,uint256,address,address,uint256)": EventFragment;
    "TakerAsk(bytes32,uint256,address,address,address,address,address,uint256,uint256,uint256)": EventFragment;
    "TakerBid(bytes32,uint256,address,address,address,address,address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CancelAllOrders"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelMultipleOrders"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewCurrencyManager"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewExecutionManager"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewProtocolFeeRecipient"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewRoyaltyFeeManager"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewTransferSelectorNFT"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoyaltyPayment"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TakerAsk"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TakerBid"): EventFragment;
}

export type CancelAllOrdersEvent = TypedEvent<
  [string, BigNumber],
  { user: string; newMinNonce: BigNumber }
>;

export type CancelAllOrdersEventFilter = TypedEventFilter<CancelAllOrdersEvent>;

export type CancelMultipleOrdersEvent = TypedEvent<
  [string, BigNumber[]],
  { user: string; orderNonces: BigNumber[] }
>;

export type CancelMultipleOrdersEventFilter =
  TypedEventFilter<CancelMultipleOrdersEvent>;

export type NewCurrencyManagerEvent = TypedEvent<
  [string],
  { currencyManager: string }
>;

export type NewCurrencyManagerEventFilter =
  TypedEventFilter<NewCurrencyManagerEvent>;

export type NewExecutionManagerEvent = TypedEvent<
  [string],
  { executionManager: string }
>;

export type NewExecutionManagerEventFilter =
  TypedEventFilter<NewExecutionManagerEvent>;

export type NewProtocolFeeRecipientEvent = TypedEvent<
  [string],
  { protocolFeeRecipient: string }
>;

export type NewProtocolFeeRecipientEventFilter =
  TypedEventFilter<NewProtocolFeeRecipientEvent>;

export type NewRoyaltyFeeManagerEvent = TypedEvent<
  [string],
  { royaltyFeeManager: string }
>;

export type NewRoyaltyFeeManagerEventFilter =
  TypedEventFilter<NewRoyaltyFeeManagerEvent>;

export type NewTransferSelectorNFTEvent = TypedEvent<
  [string],
  { transferSelectorNFT: string }
>;

export type NewTransferSelectorNFTEventFilter =
  TypedEventFilter<NewTransferSelectorNFTEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export type RoyaltyPaymentEvent = TypedEvent<
  [string, BigNumber, string, string, BigNumber],
  {
    collection: string;
    tokenId: BigNumber;
    royaltyRecipient: string;
    currency: string;
    amount: BigNumber;
  }
>;

export type RoyaltyPaymentEventFilter = TypedEventFilter<RoyaltyPaymentEvent>;

export type TakerAskEvent = TypedEvent<
  [
    string,
    BigNumber,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ],
  {
    orderHash: string;
    orderNonce: BigNumber;
    taker: string;
    maker: string;
    strategy: string;
    currency: string;
    collection: string;
    tokenId: BigNumber;
    amount: BigNumber;
    price: BigNumber;
  }
>;

export type TakerAskEventFilter = TypedEventFilter<TakerAskEvent>;

export type TakerBidEvent = TypedEvent<
  [
    string,
    BigNumber,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ],
  {
    orderHash: string;
    orderNonce: BigNumber;
    taker: string;
    maker: string;
    strategy: string;
    currency: string;
    collection: string;
    tokenId: BigNumber;
    amount: BigNumber;
    price: BigNumber;
  }
>;

export type TakerBidEventFilter = TypedEventFilter<TakerBidEvent>;

export interface LooksrareExchange extends BaseContract {
  contractName: "LooksrareExchange";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LooksrareExchangeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<[string]>;

    WETH(overrides?: CallOverrides): Promise<[string]>;

    cancelAllOrdersForSender(
      minNonce: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelMultipleMakerOrders(
      orderNonces: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    currencyManager(overrides?: CallOverrides): Promise<[string]>;

    executionManager(overrides?: CallOverrides): Promise<[string]>;

    isUserOrderNonceExecutedOrCancelled(
      user: string,
      orderNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    matchAskWithTakerBid(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    matchAskWithTakerBidUsingETHAndWETH(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    matchBidWithTakerAsk(
      takerAsk: OrderTypes.TakerOrderStruct,
      makerBid: OrderTypes.MakerOrderStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    protocolFeeRecipient(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    royaltyFeeManager(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferSelectorNFT(overrides?: CallOverrides): Promise<[string]>;

    updateCurrencyManager(
      _currencyManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateExecutionManager(
      _executionManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProtocolFeeRecipient(
      _protocolFeeRecipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateRoyaltyFeeManager(
      _royaltyFeeManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateTransferSelectorNFT(
      _transferSelectorNFT: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    userMinOrderNonce(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

  WETH(overrides?: CallOverrides): Promise<string>;

  cancelAllOrdersForSender(
    minNonce: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelMultipleMakerOrders(
    orderNonces: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  currencyManager(overrides?: CallOverrides): Promise<string>;

  executionManager(overrides?: CallOverrides): Promise<string>;

  isUserOrderNonceExecutedOrCancelled(
    user: string,
    orderNonce: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  matchAskWithTakerBid(
    takerBid: OrderTypes.TakerOrderStruct,
    makerAsk: OrderTypes.MakerOrderStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  matchAskWithTakerBidUsingETHAndWETH(
    takerBid: OrderTypes.TakerOrderStruct,
    makerAsk: OrderTypes.MakerOrderStruct,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  matchBidWithTakerAsk(
    takerAsk: OrderTypes.TakerOrderStruct,
    makerBid: OrderTypes.MakerOrderStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  protocolFeeRecipient(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  royaltyFeeManager(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferSelectorNFT(overrides?: CallOverrides): Promise<string>;

  updateCurrencyManager(
    _currencyManager: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateExecutionManager(
    _executionManager: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProtocolFeeRecipient(
    _protocolFeeRecipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateRoyaltyFeeManager(
    _royaltyFeeManager: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateTransferSelectorNFT(
    _transferSelectorNFT: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  userMinOrderNonce(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

    WETH(overrides?: CallOverrides): Promise<string>;

    cancelAllOrdersForSender(
      minNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelMultipleMakerOrders(
      orderNonces: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    currencyManager(overrides?: CallOverrides): Promise<string>;

    executionManager(overrides?: CallOverrides): Promise<string>;

    isUserOrderNonceExecutedOrCancelled(
      user: string,
      orderNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    matchAskWithTakerBid(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    matchAskWithTakerBidUsingETHAndWETH(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    matchBidWithTakerAsk(
      takerAsk: OrderTypes.TakerOrderStruct,
      makerBid: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    protocolFeeRecipient(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    royaltyFeeManager(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferSelectorNFT(overrides?: CallOverrides): Promise<string>;

    updateCurrencyManager(
      _currencyManager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateExecutionManager(
      _executionManager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProtocolFeeRecipient(
      _protocolFeeRecipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRoyaltyFeeManager(
      _royaltyFeeManager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateTransferSelectorNFT(
      _transferSelectorNFT: string,
      overrides?: CallOverrides
    ): Promise<void>;

    userMinOrderNonce(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "CancelAllOrders(address,uint256)"(
      user?: string | null,
      newMinNonce?: null
    ): CancelAllOrdersEventFilter;
    CancelAllOrders(
      user?: string | null,
      newMinNonce?: null
    ): CancelAllOrdersEventFilter;

    "CancelMultipleOrders(address,uint256[])"(
      user?: string | null,
      orderNonces?: null
    ): CancelMultipleOrdersEventFilter;
    CancelMultipleOrders(
      user?: string | null,
      orderNonces?: null
    ): CancelMultipleOrdersEventFilter;

    "NewCurrencyManager(address)"(
      currencyManager?: string | null
    ): NewCurrencyManagerEventFilter;
    NewCurrencyManager(
      currencyManager?: string | null
    ): NewCurrencyManagerEventFilter;

    "NewExecutionManager(address)"(
      executionManager?: string | null
    ): NewExecutionManagerEventFilter;
    NewExecutionManager(
      executionManager?: string | null
    ): NewExecutionManagerEventFilter;

    "NewProtocolFeeRecipient(address)"(
      protocolFeeRecipient?: string | null
    ): NewProtocolFeeRecipientEventFilter;
    NewProtocolFeeRecipient(
      protocolFeeRecipient?: string | null
    ): NewProtocolFeeRecipientEventFilter;

    "NewRoyaltyFeeManager(address)"(
      royaltyFeeManager?: string | null
    ): NewRoyaltyFeeManagerEventFilter;
    NewRoyaltyFeeManager(
      royaltyFeeManager?: string | null
    ): NewRoyaltyFeeManagerEventFilter;

    "NewTransferSelectorNFT(address)"(
      transferSelectorNFT?: string | null
    ): NewTransferSelectorNFTEventFilter;
    NewTransferSelectorNFT(
      transferSelectorNFT?: string | null
    ): NewTransferSelectorNFTEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "RoyaltyPayment(address,uint256,address,address,uint256)"(
      collection?: string | null,
      tokenId?: BigNumberish | null,
      royaltyRecipient?: string | null,
      currency?: null,
      amount?: null
    ): RoyaltyPaymentEventFilter;
    RoyaltyPayment(
      collection?: string | null,
      tokenId?: BigNumberish | null,
      royaltyRecipient?: string | null,
      currency?: null,
      amount?: null
    ): RoyaltyPaymentEventFilter;

    "TakerAsk(bytes32,uint256,address,address,address,address,address,uint256,uint256,uint256)"(
      orderHash?: null,
      orderNonce?: null,
      taker?: string | null,
      maker?: string | null,
      strategy?: string | null,
      currency?: null,
      collection?: null,
      tokenId?: null,
      amount?: null,
      price?: null
    ): TakerAskEventFilter;
    TakerAsk(
      orderHash?: null,
      orderNonce?: null,
      taker?: string | null,
      maker?: string | null,
      strategy?: string | null,
      currency?: null,
      collection?: null,
      tokenId?: null,
      amount?: null,
      price?: null
    ): TakerAskEventFilter;

    "TakerBid(bytes32,uint256,address,address,address,address,address,uint256,uint256,uint256)"(
      orderHash?: null,
      orderNonce?: null,
      taker?: string | null,
      maker?: string | null,
      strategy?: string | null,
      currency?: null,
      collection?: null,
      tokenId?: null,
      amount?: null,
      price?: null
    ): TakerBidEventFilter;
    TakerBid(
      orderHash?: null,
      orderNonce?: null,
      taker?: string | null,
      maker?: string | null,
      strategy?: string | null,
      currency?: null,
      collection?: null,
      tokenId?: null,
      amount?: null,
      price?: null
    ): TakerBidEventFilter;
  };

  estimateGas: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<BigNumber>;

    WETH(overrides?: CallOverrides): Promise<BigNumber>;

    cancelAllOrdersForSender(
      minNonce: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelMultipleMakerOrders(
      orderNonces: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    currencyManager(overrides?: CallOverrides): Promise<BigNumber>;

    executionManager(overrides?: CallOverrides): Promise<BigNumber>;

    isUserOrderNonceExecutedOrCancelled(
      user: string,
      orderNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    matchAskWithTakerBid(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    matchAskWithTakerBidUsingETHAndWETH(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    matchBidWithTakerAsk(
      takerAsk: OrderTypes.TakerOrderStruct,
      makerBid: OrderTypes.MakerOrderStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeRecipient(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    royaltyFeeManager(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferSelectorNFT(overrides?: CallOverrides): Promise<BigNumber>;

    updateCurrencyManager(
      _currencyManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateExecutionManager(
      _executionManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProtocolFeeRecipient(
      _protocolFeeRecipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateRoyaltyFeeManager(
      _royaltyFeeManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateTransferSelectorNFT(
      _transferSelectorNFT: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    userMinOrderNonce(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cancelAllOrdersForSender(
      minNonce: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelMultipleMakerOrders(
      orderNonces: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    currencyManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executionManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isUserOrderNonceExecutedOrCancelled(
      user: string,
      orderNonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    matchAskWithTakerBid(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    matchAskWithTakerBidUsingETHAndWETH(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    matchBidWithTakerAsk(
      takerAsk: OrderTypes.TakerOrderStruct,
      makerBid: OrderTypes.MakerOrderStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolFeeRecipient(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    royaltyFeeManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferSelectorNFT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateCurrencyManager(
      _currencyManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateExecutionManager(
      _executionManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProtocolFeeRecipient(
      _protocolFeeRecipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateRoyaltyFeeManager(
      _royaltyFeeManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateTransferSelectorNFT(
      _transferSelectorNFT: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    userMinOrderNonce(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
