import { MigrationInterface, QueryRunner } from 'typeorm'

export class AddTimezone1638581228549 implements MigrationInterface {

  name = 'AddTimezone1638581228549'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE "approval" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "approval" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "approval" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "approval" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "approval" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "approval" ADD "deletedAt" TIMESTAMP WITH TIME ZONE')
    await queryRunner.query('DROP INDEX "public"."IDX_8d22ddaf5542c385971071de14"')
    await queryRunner.query('DROP INDEX "public"."IDX_fcf688e53309f9b15699258fb7"')
    await queryRunner.query('DROP INDEX "public"."IDX_7bb009c7c40c5efdd372061dc4"')
    await queryRunner.query('DROP INDEX "public"."IDX_2ce892175f30a263d7f2a48890"')
    await queryRunner.query('ALTER TABLE "bid" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "bid" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "bid" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "bid" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "bid" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "bid" ADD "deletedAt" TIMESTAMP WITH TIME ZONE')
    await queryRunner.query('DROP INDEX "public"."IDX_0782d1067dcf4c7496e49a8142"')
    await queryRunner.query('DROP INDEX "public"."IDX_cff1a3063eecfa8690eb323b7d"')
    await queryRunner.query('DROP INDEX "public"."IDX_3447756fead163cc28da29f50b"')
    await queryRunner.query('DROP INDEX "public"."IDX_6daf260f04aad49c0e164fe8ac"')
    await queryRunner.query('DROP INDEX "public"."IDX_6d05b97f6bd418e7349581ce79"')
    await queryRunner.query('DROP INDEX "public"."IDX_4c27707fc3097cd748073acb32"')
    await queryRunner.query('DROP INDEX "public"."IDX_a4db743307da136f0a33734301"')
    await queryRunner.query('ALTER TABLE "edge" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "edge" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "edge" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "edge" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "edge" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "edge" ADD "deletedAt" TIMESTAMP WITH TIME ZONE')
    await queryRunner.query('DROP INDEX "public"."IDX_a985aa636a6d548ee30e68b882"')
    await queryRunner.query('DROP INDEX "public"."IDX_9bdcfe1932d4e6a2d63b6964cb"')
    await queryRunner.query('DROP INDEX "public"."IDX_91fa6acf35b7416b33a5ed0b4a"')
    await queryRunner.query('ALTER TABLE "nft" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "nft" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "nft" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "nft" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "nft" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "nft" ADD "deletedAt" TIMESTAMP WITH TIME ZONE')
    await queryRunner.query('DROP INDEX "public"."IDX_18a053d630815c9fdba26ad1ae"')
    await queryRunner.query('ALTER TABLE "profile" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "profile" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "profile" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "profile" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "profile" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "profile" ADD "deletedAt" TIMESTAMP WITH TIME ZONE')
    await queryRunner.query('ALTER TABLE "user" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "user" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "user" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "user" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "user" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "user" ADD "deletedAt" TIMESTAMP WITH TIME ZONE')
    await queryRunner.query('ALTER TABLE "wallet" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "wallet" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "wallet" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "wallet" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "wallet" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "wallet" ADD "deletedAt" TIMESTAMP WITH TIME ZONE')
    await queryRunner.query('CREATE INDEX "IDX_8d22ddaf5542c385971071de14" ON "bid" ("userId", "deletedAt", "createdAt") ')
    await queryRunner.query('CREATE INDEX "IDX_fcf688e53309f9b15699258fb7" ON "bid" ("walletId", "deletedAt", "createdAt") ')
    await queryRunner.query('CREATE INDEX "IDX_7bb009c7c40c5efdd372061dc4" ON "bid" ("profileId", "deletedAt", "createdAt") ')
    await queryRunner.query('CREATE INDEX "IDX_2ce892175f30a263d7f2a48890" ON "bid" ("profileId", "deletedAt", "price") ')
    await queryRunner.query('CREATE INDEX "IDX_6d05b97f6bd418e7349581ce79" ON "edge" ("thisEntityId", "thatEntityId", "edgeType", "deletedAt") ')
    await queryRunner.query('CREATE INDEX "IDX_0782d1067dcf4c7496e49a8142" ON "edge" ("thatEntityId", "edgeType", "deletedAt", "createdAt") ')
    await queryRunner.query('CREATE INDEX "IDX_cff1a3063eecfa8690eb323b7d" ON "edge" ("thisEntityId", "edgeType", "deletedAt", "createdAt") ')
    await queryRunner.query('CREATE INDEX "IDX_4c27707fc3097cd748073acb32" ON "edge" ("collectionId", "edgeType", "thatEntityType", "thatEntityId", "deletedAt") ')
    await queryRunner.query('CREATE INDEX "IDX_a4db743307da136f0a33734301" ON "edge" ("collectionId", "edgeType", "thatEntityType", "deletedAt") ')
    await queryRunner.query('CREATE INDEX "IDX_3447756fead163cc28da29f50b" ON "edge" ("collectionId", "edgeType", "deletedAt", "createdAt") ')
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_6daf260f04aad49c0e164fe8ac" ON "edge" ("collectionId", "edgeType", "thatEntityId", "thisEntityId", "deletedAt") ')
    await queryRunner.query('CREATE INDEX "IDX_a985aa636a6d548ee30e68b882" ON "nft" ("walletId", "deletedAt", "createdAt") ')
    await queryRunner.query('CREATE INDEX "IDX_9bdcfe1932d4e6a2d63b6964cb" ON "nft" ("userId", "deletedAt", "createdAt") ')
    await queryRunner.query('CREATE INDEX "IDX_91fa6acf35b7416b33a5ed0b4a" ON "nft" ("type", "deletedAt", "createdAt", "profileId") ')
    await queryRunner.query('CREATE INDEX "IDX_18a053d630815c9fdba26ad1ae" ON "profile" ("ownerUserId", "deletedAt", "createdAt", "status") ')
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP INDEX "public"."IDX_18a053d630815c9fdba26ad1ae"')
    await queryRunner.query('DROP INDEX "public"."IDX_91fa6acf35b7416b33a5ed0b4a"')
    await queryRunner.query('DROP INDEX "public"."IDX_9bdcfe1932d4e6a2d63b6964cb"')
    await queryRunner.query('DROP INDEX "public"."IDX_a985aa636a6d548ee30e68b882"')
    await queryRunner.query('DROP INDEX "public"."IDX_6daf260f04aad49c0e164fe8ac"')
    await queryRunner.query('DROP INDEX "public"."IDX_3447756fead163cc28da29f50b"')
    await queryRunner.query('DROP INDEX "public"."IDX_a4db743307da136f0a33734301"')
    await queryRunner.query('DROP INDEX "public"."IDX_4c27707fc3097cd748073acb32"')
    await queryRunner.query('DROP INDEX "public"."IDX_cff1a3063eecfa8690eb323b7d"')
    await queryRunner.query('DROP INDEX "public"."IDX_0782d1067dcf4c7496e49a8142"')
    await queryRunner.query('DROP INDEX "public"."IDX_6d05b97f6bd418e7349581ce79"')
    await queryRunner.query('DROP INDEX "public"."IDX_2ce892175f30a263d7f2a48890"')
    await queryRunner.query('DROP INDEX "public"."IDX_7bb009c7c40c5efdd372061dc4"')
    await queryRunner.query('DROP INDEX "public"."IDX_fcf688e53309f9b15699258fb7"')
    await queryRunner.query('DROP INDEX "public"."IDX_8d22ddaf5542c385971071de14"')
    await queryRunner.query('ALTER TABLE "wallet" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "wallet" ADD "deletedAt" TIMESTAMP')
    await queryRunner.query('ALTER TABLE "wallet" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "wallet" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "wallet" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "wallet" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "user" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "user" ADD "deletedAt" TIMESTAMP')
    await queryRunner.query('ALTER TABLE "user" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "user" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "user" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "user" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "profile" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "profile" ADD "deletedAt" TIMESTAMP')
    await queryRunner.query('ALTER TABLE "profile" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "profile" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "profile" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "profile" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('CREATE INDEX "IDX_18a053d630815c9fdba26ad1ae" ON "profile" ("createdAt", "deletedAt", "ownerUserId", "status") ')
    await queryRunner.query('ALTER TABLE "nft" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "nft" ADD "deletedAt" TIMESTAMP')
    await queryRunner.query('ALTER TABLE "nft" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "nft" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "nft" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "nft" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('CREATE INDEX "IDX_91fa6acf35b7416b33a5ed0b4a" ON "nft" ("createdAt", "deletedAt", "profileId", "type") ')
    await queryRunner.query('CREATE INDEX "IDX_9bdcfe1932d4e6a2d63b6964cb" ON "nft" ("createdAt", "deletedAt", "userId") ')
    await queryRunner.query('CREATE INDEX "IDX_a985aa636a6d548ee30e68b882" ON "nft" ("createdAt", "deletedAt", "walletId") ')
    await queryRunner.query('ALTER TABLE "edge" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "edge" ADD "deletedAt" TIMESTAMP')
    await queryRunner.query('ALTER TABLE "edge" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "edge" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "edge" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "edge" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('CREATE INDEX "IDX_a4db743307da136f0a33734301" ON "edge" ("deletedAt", "collectionId", "thatEntityType", "edgeType") ')
    await queryRunner.query('CREATE INDEX "IDX_4c27707fc3097cd748073acb32" ON "edge" ("deletedAt", "collectionId", "thatEntityId", "thatEntityType", "edgeType") ')
    await queryRunner.query('CREATE INDEX "IDX_6d05b97f6bd418e7349581ce79" ON "edge" ("deletedAt", "thisEntityId", "thatEntityId", "edgeType") ')
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_6daf260f04aad49c0e164fe8ac" ON "edge" ("deletedAt", "collectionId", "thisEntityId", "thatEntityId", "edgeType") ')
    await queryRunner.query('CREATE INDEX "IDX_3447756fead163cc28da29f50b" ON "edge" ("createdAt", "deletedAt", "collectionId", "edgeType") ')
    await queryRunner.query('CREATE INDEX "IDX_cff1a3063eecfa8690eb323b7d" ON "edge" ("createdAt", "deletedAt", "thisEntityId", "edgeType") ')
    await queryRunner.query('CREATE INDEX "IDX_0782d1067dcf4c7496e49a8142" ON "edge" ("createdAt", "deletedAt", "thatEntityId", "edgeType") ')
    await queryRunner.query('ALTER TABLE "bid" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "bid" ADD "deletedAt" TIMESTAMP')
    await queryRunner.query('ALTER TABLE "bid" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "bid" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "bid" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "bid" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('CREATE INDEX "IDX_2ce892175f30a263d7f2a48890" ON "bid" ("deletedAt", "profileId", "price") ')
    await queryRunner.query('CREATE INDEX "IDX_7bb009c7c40c5efdd372061dc4" ON "bid" ("createdAt", "deletedAt", "profileId") ')
    await queryRunner.query('CREATE INDEX "IDX_fcf688e53309f9b15699258fb7" ON "bid" ("createdAt", "deletedAt", "walletId") ')
    await queryRunner.query('CREATE INDEX "IDX_8d22ddaf5542c385971071de14" ON "bid" ("createdAt", "deletedAt", "userId") ')
    await queryRunner.query('ALTER TABLE "approval" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "approval" ADD "deletedAt" TIMESTAMP')
    await queryRunner.query('ALTER TABLE "approval" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "approval" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "approval" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "approval" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()')
  }

}
