import { MigrationInterface, QueryRunner } from 'typeorm'

export class AddCollectionEnt1639692644107 implements MigrationInterface {

  name = 'AddCollectionEnt1639692644107'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('CREATE TABLE "collection" ("id" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "items" json array NOT NULL DEFAULT \'{}\', "userId" character varying NOT NULL, CONSTRAINT "PK_ad3f485bbc99d875491f44d7c85" PRIMARY KEY ("id"))')
    await queryRunner.query('CREATE INDEX "IDX_ca25eb01f75a85272300f33602" ON "collection" ("userId") ')
    await queryRunner.query('ALTER TABLE "contract_info" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "contract_info" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "contract_info" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "contract_info" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "contract_info" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "contract_info" ADD "deletedAt" TIMESTAMP WITH TIME ZONE')
    await queryRunner.query('DROP INDEX "public"."IDX_4c27707fc3097cd748073acb32"')
    await queryRunner.query('DROP INDEX "public"."IDX_a4db743307da136f0a33734301"')
    await queryRunner.query('DROP INDEX "public"."IDX_6d05b97f6bd418e7349581ce79"')
    await queryRunner.query('DROP INDEX "public"."IDX_0782d1067dcf4c7496e49a8142"')
    await queryRunner.query('DROP INDEX "public"."IDX_cff1a3063eecfa8690eb323b7d"')
    await queryRunner.query('DROP INDEX "public"."IDX_3447756fead163cc28da29f50b"')
    await queryRunner.query('DROP INDEX "public"."IDX_6daf260f04aad49c0e164fe8ac"')
    await queryRunner.query('ALTER TYPE "public"."edge_thisentitytype_enum" RENAME TO "edge_thisentitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "public"."edge_thisentitytype_enum" AS ENUM(\'Approval\', \'Bid\', \'Collection\', \'Edge\', \'NFT\', \'Profile\', \'User\', \'Wallet\')')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "thisEntityType" TYPE "public"."edge_thisentitytype_enum" USING "thisEntityType"::"text"::"public"."edge_thisentitytype_enum"')
    await queryRunner.query('DROP TYPE "public"."edge_thisentitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."edge_thatentitytype_enum" RENAME TO "edge_thatentitytype_enum_old"')
    await queryRunner.query('CREATE TYPE "public"."edge_thatentitytype_enum" AS ENUM(\'Approval\', \'Bid\', \'Collection\', \'Edge\', \'NFT\', \'Profile\', \'User\', \'Wallet\')')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "thatEntityType" TYPE "public"."edge_thatentitytype_enum" USING "thatEntityType"::"text"::"public"."edge_thatentitytype_enum"')
    await queryRunner.query('DROP TYPE "public"."edge_thatentitytype_enum_old"')
    await queryRunner.query('ALTER TYPE "public"."edge_edgetype_enum" RENAME TO "edge_edgetype_enum_old"')
    await queryRunner.query('CREATE TYPE "public"."edge_edgetype_enum" AS ENUM(\'Follows\', \'Referred\', \'Displays\')')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "edgeType" TYPE "public"."edge_edgetype_enum" USING "edgeType"::"text"::"public"."edge_edgetype_enum"')
    await queryRunner.query('DROP TYPE "public"."edge_edgetype_enum_old"')
    await queryRunner.query('ALTER TABLE "nft_raw" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "nft_raw" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "nft_raw" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "nft_raw" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "nft_raw" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "nft_raw" ADD "deletedAt" TIMESTAMP WITH TIME ZONE')
    await queryRunner.query('ALTER TABLE "nft_trade" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "nft_trade" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "nft_trade" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "nft_trade" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "nft_trade" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "nft_trade" ADD "deletedAt" TIMESTAMP WITH TIME ZONE')
    await queryRunner.query('CREATE INDEX "IDX_6d05b97f6bd418e7349581ce79" ON "edge" ("thisEntityId", "thatEntityId", "edgeType", "deletedAt") ')
    await queryRunner.query('CREATE INDEX "IDX_0782d1067dcf4c7496e49a8142" ON "edge" ("thatEntityId", "edgeType", "deletedAt", "createdAt") ')
    await queryRunner.query('CREATE INDEX "IDX_cff1a3063eecfa8690eb323b7d" ON "edge" ("thisEntityId", "edgeType", "deletedAt", "createdAt") ')
    await queryRunner.query('CREATE INDEX "IDX_4c27707fc3097cd748073acb32" ON "edge" ("collectionId", "edgeType", "thatEntityType", "thatEntityId", "deletedAt") ')
    await queryRunner.query('CREATE INDEX "IDX_a4db743307da136f0a33734301" ON "edge" ("collectionId", "edgeType", "thatEntityType", "deletedAt") ')
    await queryRunner.query('CREATE INDEX "IDX_3447756fead163cc28da29f50b" ON "edge" ("collectionId", "edgeType", "deletedAt", "createdAt") ')
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_6daf260f04aad49c0e164fe8ac" ON "edge" ("collectionId", "edgeType", "thatEntityId", "thisEntityId", "deletedAt") ')
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP INDEX "public"."IDX_6daf260f04aad49c0e164fe8ac"')
    await queryRunner.query('DROP INDEX "public"."IDX_3447756fead163cc28da29f50b"')
    await queryRunner.query('DROP INDEX "public"."IDX_a4db743307da136f0a33734301"')
    await queryRunner.query('DROP INDEX "public"."IDX_4c27707fc3097cd748073acb32"')
    await queryRunner.query('DROP INDEX "public"."IDX_cff1a3063eecfa8690eb323b7d"')
    await queryRunner.query('DROP INDEX "public"."IDX_0782d1067dcf4c7496e49a8142"')
    await queryRunner.query('DROP INDEX "public"."IDX_6d05b97f6bd418e7349581ce79"')
    await queryRunner.query('ALTER TABLE "nft_trade" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "nft_trade" ADD "deletedAt" TIMESTAMP')
    await queryRunner.query('ALTER TABLE "nft_trade" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "nft_trade" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "nft_trade" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "nft_trade" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "nft_raw" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "nft_raw" ADD "deletedAt" TIMESTAMP')
    await queryRunner.query('ALTER TABLE "nft_raw" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "nft_raw" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "nft_raw" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "nft_raw" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('CREATE TYPE "public"."edge_edgetype_enum_old" AS ENUM(\'Follows\', \'Referred\')')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "edgeType" TYPE "public"."edge_edgetype_enum_old" USING "edgeType"::"text"::"public"."edge_edgetype_enum_old"')
    await queryRunner.query('DROP TYPE "public"."edge_edgetype_enum"')
    await queryRunner.query('ALTER TYPE "public"."edge_edgetype_enum_old" RENAME TO "edge_edgetype_enum"')
    await queryRunner.query('CREATE TYPE "public"."edge_thatentitytype_enum_old" AS ENUM(\'Approval\', \'Bid\', \'Edge\', \'NFT\', \'Profile\', \'User\', \'Wallet\')')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "thatEntityType" TYPE "public"."edge_thatentitytype_enum_old" USING "thatEntityType"::"text"::"public"."edge_thatentitytype_enum_old"')
    await queryRunner.query('DROP TYPE "public"."edge_thatentitytype_enum"')
    await queryRunner.query('ALTER TYPE "public"."edge_thatentitytype_enum_old" RENAME TO "edge_thatentitytype_enum"')
    await queryRunner.query('CREATE TYPE "public"."edge_thisentitytype_enum_old" AS ENUM(\'Approval\', \'Bid\', \'Edge\', \'NFT\', \'Profile\', \'User\', \'Wallet\')')
    await queryRunner.query('ALTER TABLE "edge" ALTER COLUMN "thisEntityType" TYPE "public"."edge_thisentitytype_enum_old" USING "thisEntityType"::"text"::"public"."edge_thisentitytype_enum_old"')
    await queryRunner.query('DROP TYPE "public"."edge_thisentitytype_enum"')
    await queryRunner.query('ALTER TYPE "public"."edge_thisentitytype_enum_old" RENAME TO "edge_thisentitytype_enum"')
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_6daf260f04aad49c0e164fe8ac" ON "edge" ("collectionId", "thisEntityId", "thatEntityId", "edgeType", "deletedAt") ')
    await queryRunner.query('CREATE INDEX "IDX_3447756fead163cc28da29f50b" ON "edge" ("collectionId", "edgeType", "createdAt", "deletedAt") ')
    await queryRunner.query('CREATE INDEX "IDX_cff1a3063eecfa8690eb323b7d" ON "edge" ("thisEntityId", "edgeType", "createdAt", "deletedAt") ')
    await queryRunner.query('CREATE INDEX "IDX_0782d1067dcf4c7496e49a8142" ON "edge" ("thatEntityId", "edgeType", "createdAt", "deletedAt") ')
    await queryRunner.query('CREATE INDEX "IDX_6d05b97f6bd418e7349581ce79" ON "edge" ("thisEntityId", "thatEntityId", "edgeType", "deletedAt") ')
    await queryRunner.query('CREATE INDEX "IDX_a4db743307da136f0a33734301" ON "edge" ("collectionId", "thatEntityType", "edgeType", "deletedAt") ')
    await queryRunner.query('CREATE INDEX "IDX_4c27707fc3097cd748073acb32" ON "edge" ("collectionId", "thatEntityId", "thatEntityType", "edgeType", "deletedAt") ')
    await queryRunner.query('ALTER TABLE "contract_info" DROP COLUMN "deletedAt"')
    await queryRunner.query('ALTER TABLE "contract_info" ADD "deletedAt" TIMESTAMP')
    await queryRunner.query('ALTER TABLE "contract_info" DROP COLUMN "updatedAt"')
    await queryRunner.query('ALTER TABLE "contract_info" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('ALTER TABLE "contract_info" DROP COLUMN "createdAt"')
    await queryRunner.query('ALTER TABLE "contract_info" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()')
    await queryRunner.query('DROP INDEX "public"."IDX_ca25eb01f75a85272300f33602"')
    await queryRunner.query('DROP TABLE "collection"')
  }

}
