export enum LoggerContext {
  Approval = 'approval',
  Bid = 'bid',
  Cache = 'cache',
  CacheDataLoader = 'dataLoaderCache',
  General = 'general',
  GraphQL = 'graphql',
  NFT = 'nft',
  PageInput = 'pageInput',
  PubSub = 'pubsub',
  Profile = 'profile',
  SendGrid = 'sendgrid',
  User = 'user',
  Wallet = 'wallet',
}
