import STS from 'aws-sdk/clients/sts'
import { Contract, Wallet } from 'ethers'
import { combineResolvers } from 'graphql-resolvers'
import { BigNumber } from 'packages/shared/node_modules/ethers/lib'

import { assetBucket } from '@nftcom/gql/config'
import { Context, gql, Pageable } from '@nftcom/gql/defs'
import { appError, approvalError, mintError, profileError, userError, walletError } from '@nftcom/gql/error'
import { auth, pagination } from '@nftcom/gql/helper'
import { core } from '@nftcom/gql/service'
import { _logger, entity,fp,helper, provider } from '@nftcom/shared'

const logger = _logger.Factory(_logger.Context.Misc, _logger.Context.GraphQL)

let cachedSTS: STS = null
const getSTS = (): STS => {
  if (helper.isEmpty(cachedSTS)) {
    cachedSTS = new STS()
  }
  return cachedSTS
}

const getFileUploadSession = (
  _: unknown,
  args: unknown,
  ctx: Context,
): Promise<gql.FileUploadOutput> => {
  const { user } = ctx
  logger.debug('getFileUploadSession', { loggedInUserId: user.id })

  const sessionName = `upload-file-to-asset-bucket-${helper.toTimestamp()}`
  const params: STS.AssumeRoleRequest = {
    RoleArn: assetBucket.role,
    RoleSessionName: sessionName,
  }

  return getSTS().assumeRole(params).promise()
    .then((response) => ({
      accessKey: response.Credentials.AccessKeyId,
      bucket: assetBucket.name,
      secretKey: response.Credentials.SecretAccessKey,
      sessionToken: response.Credentials.SessionToken,
    }))
}

const endProfileAuction = (
  _: unknown,
  args: gql.MutationEndProfileAuctionArgs,
  ctx: Context,
): Promise<gql.EndAuctionOutput> => {
  const { wallet, repositories } = ctx
  logger.debug('endProfileAuction', { walletAddress: wallet.address })

  const { input } = args
  
  // 5. send mintProfileFor Transaction

  return repositories.wallet.findById(input?.walletId)
    .then(fp.rejectIfEmpty(appError.buildNotFound(
      walletError.buildAddressNotFoundMsg(),
      walletError.ErrorType.AddressNotFound,
    )))
    .then((wallet: entity.Wallet) => wallet.userId)
    .then((userId: string) => repositories.user.findById(userId))
    .then(fp.rejectIfEmpty(appError.buildNotFound(
      userError.buildUserNotFoundMsg(''),
      userError.ErrorType.UserNotFound,
    )))
    .then((user: entity.User) => Promise.all([
      Promise.resolve(user),
      repositories.wallet.findByUserId(user.id),
    ]))
    .then(([user, wallets]: [entity.User, entity.Wallet[]]) => {
      const inputWallet = wallets.filter(w => w.id === input.walletId)[0]
      return Promise.all([
        Promise.resolve(user),
        Promise.resolve(inputWallet),
        repositories.approval.findMaxNFTApprovalByUserId(user.id)
          .then(fp.rejectIfEmpty(appError.buildNotFound(
            approvalError.buildApprovalNotFoundMsg(),
            approvalError.ErrorType.ApprovalNotFound,
          ))),
        repositories.profile.findById(input?.profileId)
          .then(fp.rejectIfEmpty(appError.buildNotFound(
            profileError.buildProfileNotFoundMsg(input?.profileId),
            profileError.ErrorType.ProfileNotFound,
          ))),
      ])
    })
    .then((
      [user, wallet, approval, profile]:
      [entity.User, entity.Wallet, entity.Approval, entity.Profile],
    ) => {
      return Promise.all([
        Promise.resolve(user),
        Promise.resolve(wallet),
        Promise.resolve(approval),
        Promise.resolve(profile),
        core.paginatedEntitiesBy(
          ctx.repositories.bid,
          { first: 1 },
          { profileId: profile.id },
          'price',
        )
          .then(pagination.toPageable({ first :1 }, 'price'))
          .then((bids: Pageable<entity.Bid>) => bids.items[0]),
      ])
    })
    .then(async ([user, wallet, approval, profile, topBid]) => {
      if (BigNumber.from(approval.amount).lt(BigNumber.from(topBid.price))) {
        return Promise.reject(appError.buildInvalid(
          approvalError.buildApprovalInsufficientMsg(),
          approvalError.ErrorType.ApprovalInsufficient,
        ))
      }
      if (topBid.walletId !== wallet.id) {
        return Promise.reject(appError.buildInvalid(
          mintError.buildWalletLosingMsg(),
          mintError.ErrorType.WalletLosing,
        ))
      }
      const overrides = {
        // The maximum units of gas for the transaction to use
        gasLimit: 1500000,
        gasPrice: Number(10) * 1000000000, // wei
      }
      // TODO default to ETH mainnet
      const signer = Wallet.fromMnemonic(process.env.MNEMONIC)
        .connect(provider.provider(wallet.chainId))
      const profileAuctionContract = new Contract(
        // TODO: use real address helper
        // getAddress('profileAuction', process.env.CHAIN_ID),
        '0x0684cb6f6dF529135E591b1F15028b57185d3195',
        // getABI('profileAuction', process.env.CHAIN_ID),
        // TODO: use real ABI generated by typechain
        'ABI',
        signer,
      )
      const tx = await profileAuctionContract.mintProfileFor(
        topBid.price,
        profile.url,
        wallet.address,
        topBid.signature.v,
        topBid.signature.r,
        topBid.signature.s,
        approval.signature.v,
        approval.signature.r,
        approval.signature.s,
        overrides,
      )

      const hash = tx.hash
      return Promise.all([
        Promise.resolve(user),
        Promise.resolve(wallet),
        Promise.resolve(approval),
        Promise.resolve(profile),
        Promise.resolve(topBid),
        provider.provider(wallet.chainId).waitForTransaction(hash),
      ])
    })
    .then(([user, wallet, approval, profile, topBid, receipt]) => {
      // TODO: create NFT ent representing new Profile
      // TODO: mutate topBid.status
      // TODO: mutate profile.status
      console.log({ user, wallet, approval, profile, topBid, receipt })

      return null
    })
}

export default {
  Mutation: {
    uploadFileSession: combineResolvers(auth.isAuthenticated, getFileUploadSession),
    endProfileAuction: combineResolvers(auth.isTeamAuthenticated, endProfileAuction),
  },
}
