/* eslint-disable max-len */
import { MigrationInterface, QueryRunner } from 'typeorm'

export class Genesis1635976109755 implements MigrationInterface {

  name = 'Genesis1635976109755'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('CREATE TABLE "approval" ("id" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "amount" integer NOT NULL, "deadline" character varying NOT NULL, "nonce" integer NOT NULL, "signature" json NOT NULL, "txHash" character varying NOT NULL, "userId" character varying NOT NULL, "walletId" character varying NOT NULL, CONSTRAINT "PK_97bfd1cd9dff3c1302229da6b5c" PRIMARY KEY ("id"))')
    await queryRunner.query('CREATE INDEX "IDX_f72b9f75117746878f7b44012e" ON "approval" ("userId") ')
    await queryRunner.query('CREATE INDEX "IDX_2ca1849f697a2a1eda435863fa" ON "approval" ("walletId") ')
    await queryRunner.query('CREATE TYPE "public"."bid_nfttype_enum" AS ENUM(\'ERC721\', \'ERC1155\', \'Profile\')')
    await queryRunner.query('CREATE TYPE "public"."bid_status_enum" AS ENUM(\'Executed\', \'Submitted\')')
    await queryRunner.query('CREATE TABLE "bid" ("id" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "nftType" "public"."bid_nfttype_enum" NOT NULL, "price" integer NOT NULL, "profileId" character varying, "signature" json NOT NULL, "stakeWeightedSeconds" integer, "status" "public"."bid_status_enum" NOT NULL, "userId" character varying NOT NULL, "walletId" character varying NOT NULL, CONSTRAINT "PK_ed405dda320051aca2dcb1a50bb" PRIMARY KEY ("id"))')
    await queryRunner.query('CREATE INDEX "IDX_8898792509b9d174c32d5f10ed" ON "bid" ("profileId") ')
    await queryRunner.query('CREATE INDEX "IDX_b0f254bd6d29d3da2b6a8af262" ON "bid" ("userId") ')
    await queryRunner.query('CREATE INDEX "IDX_e5fe9523948edab80df1cb14ea" ON "bid" ("walletId") ')
    await queryRunner.query('CREATE TYPE "public"."edge_thisentitytype_enum" AS ENUM(\'Approval\', \'Bid\', \'Edge\', \'NFT\', \'Profile\', \'User\', \'Wallet\')')
    await queryRunner.query('CREATE TYPE "public"."edge_thatentitytype_enum" AS ENUM(\'Approval\', \'Bid\', \'Edge\', \'NFT\', \'Profile\', \'User\', \'Wallet\')')
    await queryRunner.query('CREATE TYPE "public"."edge_edgetype_enum" AS ENUM(\'Follows\')')
    await queryRunner.query('CREATE TABLE "edge" ("id" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "collectionId" character varying, "thisEntityId" character varying NOT NULL, "thisEntityType" "public"."edge_thisentitytype_enum" NOT NULL, "thatEntityId" character varying NOT NULL, "thatEntityType" "public"."edge_thatentitytype_enum" NOT NULL, "edgeType" "public"."edge_edgetype_enum" NOT NULL, CONSTRAINT "PK_bf6f43c9af56d05094d8c57b311" PRIMARY KEY ("id"))')
    await queryRunner.query('CREATE INDEX "IDX_6d05b97f6bd418e7349581ce79" ON "edge" ("thisEntityId", "thatEntityId", "edgeType", "deletedAt") ')
    await queryRunner.query('CREATE INDEX "IDX_0782d1067dcf4c7496e49a8142" ON "edge" ("thatEntityId", "edgeType", "deletedAt", "createdAt") ')
    await queryRunner.query('CREATE INDEX "IDX_cff1a3063eecfa8690eb323b7d" ON "edge" ("thisEntityId", "edgeType", "deletedAt", "createdAt") ')
    await queryRunner.query('CREATE INDEX "IDX_a4db743307da136f0a33734301" ON "edge" ("collectionId", "edgeType", "thatEntityType", "deletedAt") ')
    await queryRunner.query('CREATE INDEX "IDX_3447756fead163cc28da29f50b" ON "edge" ("collectionId", "edgeType", "deletedAt", "createdAt") ')
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_05675ffabd0e7411d60f1c8a3f" ON "edge" ("collectionId", "edgeType", "thatEntityId", "thisEntityId") ')
    await queryRunner.query('CREATE TYPE "public"."nft_type_enum" AS ENUM(\'ERC721\', \'ERC1155\', \'Profile\')')
    await queryRunner.query('CREATE TABLE "nft" ("id" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "contract" character varying, "metadata" json NOT NULL, "price" integer NOT NULL, "profileId" character varying, "type" "public"."nft_type_enum" NOT NULL, "userId" character varying NOT NULL, "walletId" character varying NOT NULL, CONSTRAINT "PK_8f46897c58e23b0e7bf6c8e56b0" PRIMARY KEY ("id"))')
    await queryRunner.query('CREATE INDEX "IDX_6d1d3e44255e3e0cbf68abb3a3" ON "nft" ("profileId") ')
    await queryRunner.query('CREATE INDEX "IDX_2d4535b902eed75d0deb2d515b" ON "nft" ("userId") ')
    await queryRunner.query('CREATE INDEX "IDX_507e94bbcf55ced306bf3b72e7" ON "nft" ("walletId") ')
    await queryRunner.query('CREATE TABLE "profile" ("id" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "url" character varying NOT NULL, "creatorUserId" character varying NOT NULL, "ownerUserId" character varying NOT NULL, "creatorWalletId" character varying NOT NULL, "ownerWalletId" character varying NOT NULL, CONSTRAINT "PK_3dd8bfc97e4a77c70971591bdcb" PRIMARY KEY ("id"))')
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_5fbce8b9bbd1cf934117f492d4" ON "profile" ("url") ')
    await queryRunner.query('CREATE INDEX "IDX_99ebb4d1a58a8b1f97593402cd" ON "profile" ("ownerUserId") ')
    await queryRunner.query('CREATE TABLE "user" ("id" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "email" character varying NOT NULL, "isEmailConfirmed" boolean NOT NULL DEFAULT false, "confirmEmailToken" integer, "confirmEmailTokenExpiresAt" TIMESTAMP, "avatarURL" character varying, "referredBy" character varying, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "UQ_4007f003f9899ca1c146097eff9" UNIQUE ("confirmEmailToken"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))')
    await queryRunner.query('CREATE INDEX "IDX_e12875dfb3b1d92d7d7c5377e2" ON "user" ("email") ')
    await queryRunner.query('CREATE TABLE "wallet" ("id" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" character varying NOT NULL, "chainId" character varying NOT NULL, "chainName" character varying NOT NULL, "network" character varying NOT NULL, "address" character varying NOT NULL, CONSTRAINT "PK_bec464dd8d54c39c54fd32e2334" PRIMARY KEY ("id"))')
    await queryRunner.query('CREATE INDEX "IDX_35472b1fe48b6330cd34970956" ON "wallet" ("userId") ')
    await queryRunner.query('CREATE UNIQUE INDEX "IDX_d961f78eb041ecc84687fea35a" ON "wallet" ("chainId", "address", "network") ')
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP INDEX "public"."IDX_d961f78eb041ecc84687fea35a"')
    await queryRunner.query('DROP INDEX "public"."IDX_35472b1fe48b6330cd34970956"')
    await queryRunner.query('DROP TABLE "wallet"')
    await queryRunner.query('DROP INDEX "public"."IDX_e12875dfb3b1d92d7d7c5377e2"')
    await queryRunner.query('DROP TABLE "user"')
    await queryRunner.query('DROP INDEX "public"."IDX_99ebb4d1a58a8b1f97593402cd"')
    await queryRunner.query('DROP INDEX "public"."IDX_5fbce8b9bbd1cf934117f492d4"')
    await queryRunner.query('DROP TABLE "profile"')
    await queryRunner.query('DROP INDEX "public"."IDX_507e94bbcf55ced306bf3b72e7"')
    await queryRunner.query('DROP INDEX "public"."IDX_2d4535b902eed75d0deb2d515b"')
    await queryRunner.query('DROP INDEX "public"."IDX_6d1d3e44255e3e0cbf68abb3a3"')
    await queryRunner.query('DROP TABLE "nft"')
    await queryRunner.query('DROP TYPE "public"."nft_type_enum"')
    await queryRunner.query('DROP INDEX "public"."IDX_05675ffabd0e7411d60f1c8a3f"')
    await queryRunner.query('DROP INDEX "public"."IDX_3447756fead163cc28da29f50b"')
    await queryRunner.query('DROP INDEX "public"."IDX_a4db743307da136f0a33734301"')
    await queryRunner.query('DROP INDEX "public"."IDX_cff1a3063eecfa8690eb323b7d"')
    await queryRunner.query('DROP INDEX "public"."IDX_0782d1067dcf4c7496e49a8142"')
    await queryRunner.query('DROP INDEX "public"."IDX_6d05b97f6bd418e7349581ce79"')
    await queryRunner.query('DROP TABLE "edge"')
    await queryRunner.query('DROP TYPE "public"."edge_edgetype_enum"')
    await queryRunner.query('DROP TYPE "public"."edge_thatentitytype_enum"')
    await queryRunner.query('DROP TYPE "public"."edge_thisentitytype_enum"')
    await queryRunner.query('DROP INDEX "public"."IDX_e5fe9523948edab80df1cb14ea"')
    await queryRunner.query('DROP INDEX "public"."IDX_b0f254bd6d29d3da2b6a8af262"')
    await queryRunner.query('DROP INDEX "public"."IDX_8898792509b9d174c32d5f10ed"')
    await queryRunner.query('DROP TABLE "bid"')
    await queryRunner.query('DROP TYPE "public"."bid_status_enum"')
    await queryRunner.query('DROP TYPE "public"."bid_nfttype_enum"')
    await queryRunner.query('DROP INDEX "public"."IDX_2ca1849f697a2a1eda435863fa"')
    await queryRunner.query('DROP INDEX "public"."IDX_f72b9f75117746878f7b44012e"')
    await queryRunner.query('DROP TABLE "approval"')
  }

}
