encryptionsalt: v1:BBAXw9kJQZ4=:v1:MadP9xMf3KNOBrBb:GAQRdszs2dk0GTHxxIt+OiyCqPa5Nw==
config:
  nftcom:availabilityZones: us-east-1a,us-east-1b,us-east-1c
  nftcom:auroraMainInstances: 2
  nftcom:auroraMainInstance: db.r6g.xlarge
  nftcom:redisMainInstance: cache.m6g.large
