name: Cronjobs github actions
on: 
  push: 
    paths: 
      - '.github/actions/deploy-cronjobs/action.yml'
      - '.github/workflows/cronjobs.yml'
      - 'cronjobs/**'
      - 'infra/cronjobs/**'
jobs: 
  deploy-dev-cronjobs:
    if: ${{ github.ref_name == 'develop' || (startsWith(github.ref_name, 'feat') || startsWith(github.ref_name, 'fix') }}
    runs-on: ubuntu-latest
    environment: nftcom_dev_cronjobs
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-cronjobs
        name: Deploy Cronjobs [Dev] 
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: dev
  deploy-staging-cronjobs:
    if: ${{ startsWith(github.ref_name, 'release') }}
    runs-on: ubuntu-latest
    environment: nftcom_staging_cronjobs
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-cronjobs
        name: Deploy cronjobs [staging]
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: staging
  deploy-prod-cronjobs:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    environment: nftcom_prod_cronjobs
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-cronjobs
        name: Deploy cronjobs [prod]
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: prod
