name: Cross Account github actions TEST
on:
  push: 
    paths: 
      - '.github/actions/deploy-crossaccount/action.yml'
      - '.github/workflows/cross-account.yml'
      - 'infra/cross-account*/**'
jobs: 
  deploy-immutable-cross-account:
    runs-on: ubuntu-latest
    environment: nftcom_dev_streamingfast
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-crossaccount
        name: Deploy cross account stack [Dev] 
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: dev
          account: developer