name: NFT.com github actions
on: 
  push: 
    paths: 
      - 'packages/**'
      - 'perftest/**'
      - 'gql/**'
      - 'infra/gql/**'
      - 'infra/shared/**'
      - 'infra/deps/**'
      - 'infra/helper/**'
      - 'infra/index**'
      - 'infra/pacakage**'
jobs:
  deploy-dev:
    needs: deployment-triggers
    if: ${{ github.ref_name == 'develop' }}
    runs-on: [self-hosted]
    environment: nftcom_dev
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-env
        name: Deploy GQL Env [Dev] 
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: dev
  deploy-staging:
    needs: deployment-triggers
    if: ${{ startsWith(github.ref_name, 'release') }}
    runs-on: [self-hosted]
    environment: nftcom_staging
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-env
        name: Deploy GQL Env [Staging] 
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: staging
  deploy-prod:
    if: ${{ github.ref_name == 'main' }}
    runs-on: [self-hosted]
    environment: nftcom_prod
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-env
        name: Deploy GQL Env [Prod] 
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: prod
