name: NFT.com github actions
on: [push]
jobs:
  deploy-dev:
    if: ${{ startsWith(github.ref_name, 'feat') || startsWith(github.ref_name, 'fix') }}
    runs-on: ubuntu-latest
    environment: nftcom_dev
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            gql:
             - 'packages/**'
             - 'perftest/**'
             - 'package**'
             - 'gql**'
            infra:
             - 'infra/gql/**'
             - 'infra/shared/**'
             - 'infra/defs/**'
             - 'infra/helper/**'
      - name: Deploy GQL Env [Dev] 
        if: ${{ steps.filter.outputs.gql == 'true' || steps.filter.outputs.infra == 'true' }}
        uses: ./.github/actions/deploy-env
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: dev
  deploy-staging:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    environment: nftcom_staging
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-env
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: staging
  deploy-prod:
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'rel') }}
    runs-on: ubuntu-latest
    environment: nftcom_prod
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-env
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: prod
  deploy-dev-cronjobs:
    if: ${{ startsWith(github.ref_name, 'featJob') || startsWith(github.ref_name, 'fixJob') }}
    runs-on: ubuntu-latest
    environment: nftcom_dev_cronjobs
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            cronjobs:
              - 'cronjobs/**'
              - 'infra/cronjobs/**'
      - name: Deploy Cronjobs [Dev] 
        if: ${{ steps.filter.outputs.cronjobs == 'true' }}
        uses: ./.github/actions/deploy-cronjobs
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: dev
  deploy-staging-cronjobs:
    if: ${{ github.ref_name == 'main' }} # to do: find way to seperate gql/cronjob staging deployment
    runs-on: ubuntu-latest
    environment: nftcom_staging_cronjobs
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-cronjobs
        name: Deploy cronjobs [staging]
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: staging
  deploy-prod-cronjobs:
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'relJob') }}
    runs-on: ubuntu-latest
    environment: nftcom_prod_cronjobs
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-cronjobs
        name: Deploy cronjobs [prod]
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: prod