name: GQL Performance Test

on: [push]

jobs:
  perftest:

    runs-on: ubuntu-latest
    environment: nftcom_dev

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install k6
      run: |
        cd perftest/gql
        curl https://github.com/grafana/k6/releases/download/v0.38.3/k6-v0.38.3-linux-amd64.tar.gz -L | tar xvz --strip-components 1
    
    - name: k6 test (home page api)
      run: cd perftest/gql && npm run start:ci

    - name: k6 test (mint profile page api)
      run: cd perftest/gql && QUERY_DIR=mint-profile npm run start:ci