name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        AUTH_MESSAGE: ${{ secrets.AUTH_MESSAGE }}
        SG_API_KEY: ${{ secrets.SG_API_KEY }}
        ETH_GAS_STATION_API_KEY: ${{ secrets.ETH_GAS_STATION_API_KEY }}
        PROFILE_AUCTION_END_PASSWORD: ${{ secrets.PROFILE_AUCTION_END_PASSWORD }}
        MNEMONIC: ${{ secrets.MNEMONIC }}
        MNEMONIC_RINKEBY: ${{ secrets.MNEMONIC_RINKEBY }}
        HCS_TOPIC_ID: ${{ secrets.HCS_TOPIC_ID }}
        HCS_ACCOUNT_ID: ${{ secrets.HCS_ACCOUNT_ID }}
        HCS_PRIVATE_KEY: ${{ secrets.HCS_PRIVATE_KEY }}
        ZMOK_API_URL: ${{ secrets.ZMOK_API_URL }}
        INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        ALCHEMY_API_URL: ${{ secrets.ALCHEMY_API_URL }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        PUBLIC_SALE_KEY: ${{ secrets.PUBLIC_SALE_KEY }}
        SERVER_CONFIG: ${{ secrets.SERVER_CONFIG }}
        SHARED_MINT_SECRET: ${{ secrets.SHARED_MINT_SECRET }}
        SUPPORTED_NETWORKS: ${{ secrets.SUPPORTED_NETWORKS }}
        TYPESENSE_HOST: ${{ secrets.TYPESENSE_HOST }}
        TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
        MINTED_PROFILE_EVENTS_MAX_BLOCKS: ${{ secrets.MINTED_PROFILE_EVENTS_MAX_BLOCKS }}
        PROFILE_NFTS_EXPIRE_DURATION: ${{ secrets.PROFILE_NFTS_EXPIRE_DURATION }}
        BULL_MAX_REPEAT_COUNT: ${{ secrets.BULL_MAX_REPEAT_COUNT }}
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # - name: Cache node modules
    #   id: cache-npm
    #   uses: actions/cache@v3
    #   env:
    #     cache-name: cache-node-modules
    #   with:
    #     path: ~/.npm
    #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    #     restore-keys: |
    #       ${{ runner.os }}-build-${{ env.cache-name }}-
    #       ${{ runner.os }}-build-
    #       ${{ runner.os }}-

    # - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
    #   name: List the state of node modules
    #   continue-on-error: true
    #   run: npm list
    
    - run: npm i
    - run: cd packages/gql && npm i
    - run: cd packages/shared && npm i
    - run: cd packages/shared && npm run compile
    - run: cd packages/gql && npm run gql:gen
    - run: cd packages/gql && npm run test
